### ISSUE TITLE
2018-06 TODO list

### ISSUE THREAD

**Issue by chalin** [chalin/code_excerpter#2]
- [x] Support plaster #3
- [ ] Add minimal useful content to `README.md`
- [ ] Support, or at least warn about / reject, excerpts who first line is indented more than the rest.

Later:
- [ ] Region name generalization: we're considering supporting quoted region names. Ensure that this is handled properly when encoding the region name as a key in the YAML file.
